name: Run

on: 
  workflow_dispatch:
#   schedule:
#     - cron: '*/15 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - run: |
        sed -i "s|webhookurl|${LOG_DISCORD_WEBHOOK_URL}|g" configs/mainconf.ini
        sed -i "s|webhookurl|${DISCORD_WEBHOOK_URL}|g" configs/plane1.ini
      env:
        LOG_DISCORD_WEBHOOK_URL: ${{ secrets.LOG_DISCORD_WEBHOOK_URL }}
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}

    - run: docker build -t plane-notify .
    
    - run: docker run plane-notify
